<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <LangVersion>8.0</LangVersion>
    <Version>1.0.5</Version>
    <Authors>Tom Birras</Authors>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Description>Basic components for PandaSharp wrappers</Description>
    <PackageProjectUrl>https://github.com/Metablex/PandaSharp.Framework</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="RestSharp" Version="112.1.0" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>PandaSharp.Framework.Test</_Parameter1>
    </AssemblyAttribute>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>DynamicProxyGenAssembly2</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

</Project>
